import Head from "next/head";
import requests from "../utils/requests";

import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ results }) {
  return (
    <div className="dark">
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* Header part */}
        <Header />
        {/* Nav Bar */}
        <Nav />
        {/* Results */}
        <Results results={results} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
