import Head from "next/head";
import request from "../utils/request";

import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Nav from "../components/Nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  console.log(props);
  return (
    <div className="dark">
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* Header part */}
        <Header />
        {/* Nav Bar */}
        <Nav />
        {/* Results */}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const requests = await fetch(
    `https://api.themoviedb.org/3${
      request[genre]?.url || request.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: requests.results,
    },
  };
}
